### ISSUE TITLE
StfAgent doesn't run on Android S DP3

### ISSUE THREAD

**Issue by pcrepieux** [DeviceFarmer/STFService.apk#37]
Here is the stacktrace showing that a method called through reflection doesn't exist anymore.
```
04-30 09:24:54.906 31651 31651 D AndroidRuntime: Calling main entry jp.co.cyberagent.stf.Agent
04-30 09:24:54.911 31651 31667 I MinitouchAgent: creating socket minitouchagent
04-30 09:24:54.911 31651 31667 I MinitouchAgent: Listening on minitouchagent
04-30 09:24:54.912 31651 31668 E AndroidRuntime: FATAL EXCEPTION: Thread-2
04-30 09:24:54.912 31651 31668 E AndroidRuntime: PID: 31651
04-30 09:24:54.912 31651 31668 E AndroidRuntime: java.lang.UnsupportedOperationException: UserActivityWakeInjector is not supported
04-30 09:24:54.912 31651 31668 E AndroidRuntime: at jp.co.cyberagent.stf.compat.PowerManagerWrapper$OldUserActivityWakeInjector.<init>(PowerManagerWrapper.java:121)
04-30 09:24:54.912 31651 31668 E AndroidRuntime: at jp.co.cyberagent.stf.compat.PowerManagerWrapper.<init>(PowerManagerWrapper.java:26)
04-30 09:24:54.912 31651 31668 E AndroidRuntime: at jp.co.cyberagent.stf.Agent.run(Agent.java:124)
04-30 09:24:54.914  1644  2676 I DropBoxManagerService: add tag=system_server_crash isTagEnabled=true flags=0x2
04-30 09:24:54.915 31651 31668 I Process : Sending signal. PID: 31651 SIG: 9
```

**Comment by Chadarr** [comment]
Compiled APK with these changes
STFService is finally able to start, device is shown as ready to use in STF web console
But when I start using device, another crash happens
```
05-31 16:18:58.655  8312  8339 W .cyberagent.st: Accessing hidden method Landroid/view/IWindowManager$Stub$Proxy;->getDefaultDisplayRotation()I (max-target-o, reflection, denied)
05-31 16:18:58.655  8312  8339 W .cyberagent.st: Accessing hidden method Landroid/view/IWindowManager;->getDefaultDisplayRotation()I (max-target-o, reflection, denied)
05-31 16:18:58.655  8312  8339 W System.err: java.lang.NoSuchMethodException: android.view.IWindowManager$Stub$Proxy.getRotation []
05-31 16:18:58.655  8312  8339 W System.err: 	at java.lang.Class.getMethod(Class.java:2103)
05-31 16:18:58.655  8312  8339 W System.err: 	at java.lang.Class.getMethod(Class.java:1724)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.compat.WindowManagerWrapper.getRotation(WindowManagerWrapper.java:65)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.monitor.RotationMonitor.peek(RotationMonitor.java:54)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.Service$Server$Connection.run(Service.java:369)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by pcrepieux** [comment]
@Chadarr, could you provide more logs, I am not sure this error can cause a crash.

**Comment by pcrepieux** [comment]
Thanks for the log @Chadarr 
I think your issue is related to [minicap](https://github.com/DeviceFarmer/minicap) :
`06-08 11:25:03.766 20287 20287 F linker  : CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": cannot locate symbol "_ZN7android21SurfaceComposerClient23getPhysicalDisplayTokenEm" referenced by "/data/local/tmp/minicap.so"...`
It's been fixed with https://github.com/DeviceFarmer/stf/pull/262

**Comment by sudhalucky** [comment]
Hi @pcrepieux , I am able to get it working on Android 12 however when I rotate the screen to landscape in STF the screen resolution stays in portrait and the device screen of landscape is skewed to portrait resolution and scaled instead of rendering it in Landscape resolution.
Note: Other devices Pixel and non Pixel on Android-11 and below work fine as expected, this is only happening on Pixel with Android-12, can you please help?

![portrait-android-12](https://user-images.githubusercontent.com/6541814/122794388-d482a500-d2d9-11eb-9e0c-ad86dcc902ac.png)
![landscape-android-12](https://user-images.githubusercontent.com/6541814/122794395-d5b3d200-d2d9-11eb-8a75-64cd1c6c21ae.png)

**Comment by pcrepieux** [comment]
@sudhalucky, 
Indeed I also noticed it. That's more likely an issue with https://github.com/DeviceFarmer/minicap. 
I am on it.

**Comment by sudhalucky** [comment]
HI @pcrepieux  How are you? Were you able to get this sorted. Let me know if I can try something on my side if you are busy.

**Comment by pcrepieux** [comment]
Currently testing the fix for proper rotation handling. Will push the updated code shortly (please refer to https://github.com/DeviceFarmer/minicap/issues/17)

As the initial issue is already fixed (https://github.com/DeviceFarmer/STFService.apk/pull/42) and the other one mentioned in this thread doesn't seems related (https://github.com/DeviceFarmer/stf/pull/262), let's close this
