### ISSUE TITLE
STFService can not return all apps on my HUAWEI phone(base on Android 10)

### ISSUE THREAD

**Issue by suzhenyu006** [DeviceFarmer/STFService.apk#39]
there are two methods can find apps
![image](https://user-images.githubusercontent.com/38517127/117524043-5058b480-afee-11eb-9df3-634e7ffd49a3.png)

but when i print the result , there was only one app
![image](https://user-images.githubusercontent.com/38517127/117524071-7716eb00-afee-11eb-85ff-54c5ed650250.png)
 
this is my phone:
![image](https://user-images.githubusercontent.com/38517127/117524128-cd842980-afee-11eb-800c-94a3b63cd5e4.png)

it have many browser apps

**Comment by koral--** [comment]
Seems to be fixed by #101
